global:
  chartName: products
products:
  # Deployment object
  deployment:
    enabled: true
    name: products
    namespace: ecommerce
    replicas: 3
    appName: products
    role: api
    containerName: products-container
    imageRepository: ghcr.io/alex00pep/ecommerce-products
    imageTag: 0.1.5
    port: 3004
  # Updated (New) Deployment resource
  newDeployment:
    enabled: false
  # Stable Service object
  service:
    enabled: true
    name: products-service
    namespace: ecommerce
    appName: products
    type: ClusterIP
    servicePort: 3004
    targetPort: 3004
  # Canary Service object
  canaryService:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: products-service-account
    namespace: ecommerce
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:    
    name: products-dev-ingress
    namespace: ecommerce-dev
    enabled: true
    host: products-dev.nane02.home.techfitsu.org
    path: /
    serviceName: products-service
    servicePort: 3004
    className: traefik
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Canary Rollout
  canaryRollout:
    enabled: false
