global:
  chartName: orders
orders:
  # Deployment object
  deployment:
    enabled: false
  # Updated (New) Deployment resource
  newDeployment:
    enabled: true
    name: orders
    namespace: ecommerce-dev
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: ghcr.io/alex00pep/ecommerce-orders
    imageTag: sha256:335028611428a7c2a3139fd9dff042e3efbb83b70a2bbac6adf7813b347556cc
    port: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce-dev
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce-dev
    appName: orders
    type: ClusterIP
    servicePort: 3003
    targetPort: 3003
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    name: orders-dev-ingress
    namespace: ecommerce-dev
    enabled: true
    host: orders-dev.nane02.home.techfitsu.org
    path: /
    serviceName: orders-service
    servicePort: 3003
    className: traefik
    tls:
      enabled: true
      secretName: home-production-tls
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
